name: Publish

on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build
        shell: bash
        run: |
          # Clean and setup build directory
          if [ -d "./Pivet/bin/Release/net8.0/publish/" ]; then
            rm -rf "./Pivet/bin/Release/net8.0/"
          fi
          
          if [ ! -d "./build" ]; then
            mkdir build
          fi
          
          # Get commit hash for naming
          hash=$(git rev-parse HEAD | cut -c1-7)
          
          # Build Linux
          dotnet publish ./Pivet/Pivet.csproj /p:PublishProfile=Linux /p:Configuration=Release -f net8.0
          cd "./Pivet/bin/Release/net8.0/linux-x64"
          zip -r "../../../../../build/linux-$hash.zip" .
          cd "../../../../../"
          
          # Build Windows  
          dotnet publish ./Pivet/Pivet.csproj /p:PublishProfile=Windows /p:Configuration=Release -f net8.0
          cd "./Pivet/bin/Release/net8.0/win-x64"
          zip -r "../../../../../build/windows-$hash.zip" .
          cd "../../../../../"
          
          # Build Linux Self-Contained
          dotnet publish ./Pivet/Pivet.csproj /p:PublishProfile=LinuxSelfContained /p:Configuration=Release -f net8.0
          cd "./Pivet/bin/Release/net8.0/linux-x64"
          zip -r "../../../../../build/linux-self-contained-$hash.zip" .
          cd "../../../../../"
          
          # Build Windows Self-Contained
          dotnet publish ./Pivet/Pivet.csproj /p:PublishProfile=WindowsSelfContained /p:Configuration=Release -f net8.0
          cd "./Pivet/bin/Release/net8.0/win-x64"
          zip -r "../../../../../build/windows-self-contained-$hash.zip" .
          cd "../../../../../"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "./build/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}